---
name: Debug
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  new-pr-debug:
    if: (github.event.action == 'opened' || github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    steps:
      - uses: dustindortch/github-action-explore-debug@main
        with:
          jq_selector: "."

  merge-pr-debug:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: dustindortch/github-action-explore-debug@main
        with:
          jq_selector: "."
...