---
name: Debug
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  output-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: dustindortch/github-action-explore-debug
        with:
          jq_selector: ".pull_request"
...