---
name: Debug
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - destroy

permissions:
  actions: read
  contents: read
  id-token: write
  pull-requests: write

jobs:
  new-pr-debug:
    if: (github.event.action == 'opened' || github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    steps:
      - uses: dustindortch/github-action-explore-debug@main
        with:
          jq_selector: "."

  merge-pr-debug:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: dustindortch/github-action-explore-debug@main
        with:
          jq_selector: "."


      - id: output_head_sha
        env:
          HEAD_COMMIT: ${{ github.event.pull_request.head.sha }}
        run: echo "${HEAD_COMMIT}"

  manual_trigger:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - id: return_event
        run: |
          echo "${{fromJson(github.event)}}"
...
